name: Deploy to Firebase Functions

on:
  push:
    branches:
      - master  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # specify your Node.js version
    - name: Install Dependencies
      run: npm install
      working-directory: ./functions
    - name: Find and Replace REACT_APP_GOOGLE_DEV_KEY
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "REACT="
        replace: "REACT=${{ secrets.MY_VAR }}"
        include: "**.env"

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}